### ISSUE TITLE
A missing USGS station

### ISSUE THREAD

**Issue by cheginit** [internetofwater/ref_gages#22]
The following USGS station is not indexed:

ID: [04127918](https://waterdata.usgs.gov/monitoring-location/04127918/#parameterCode=00060&period=P7D)
nhdplusv2 comid: 12206226
nhdplusv2 reachcode: 04070002000042

**Comment by cheginit** [comment]
I found two other stations:

ID: [02084557](https://waterdata.usgs.gov/nc/nwis/uv?02084557)
nhdplusv2 comid: 1967611
nhdplusv2 reachcode: 03020104000870

ID: [10172200](https://waterdata.usgs.gov/usa/nwis/uv?10172200)
nhdplusv2 comid: 10389446
nhdplusv2 reachcode: 16020204000450

**Comment by dblodgett-usgs** [comment]
Are you sure about those last two? I don't have time to dig into things (and I found a bug I need to fix) but it seems like they are not really in the vicinity of the gage. Maybe I'm not looking at things right.

**Comment by cheginit** [comment]
These are the flowline-station distances in meters:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/13016644/156964926-690d6a53-6636-438b-9fe1-474aa9e36d2f.png">

I used NLDI's position endpoint to get the nearest comid. The last two sound far from the stations.

**Comment by dblodgett-usgs** [comment]
OK -- yeah, that's what I'm seeing. 

So it seems like there just is no flowline for the two that are far away?

**Comment by cheginit** [comment]
No, there's no nearby flowline in nhdplus mr, but there are in nhdplus hr:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/13016644/157102099-1f6887e1-d12c-40e6-b3b2-f49e876105ea.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/13016644/157102127-930aa345-1222-4907-bd24-3d16a7a1cd9c.png">

**Comment by dblodgett-usgs** [comment]
OK, re: the one you found missing, I found the issue. It was superseded by 04127917 -- but the record wasn't combined. In my source of network locations that is the highest quality, they dropped 04127918. I will bring these cases back in our next release of locations to the NLDI.

**Comment by dblodgett-usgs** [comment]
Regarding the ones that are far from a medium res flowline -- I don't think we should put those into the NLDI as indexed gages. We don't currently have a hybrid approach though. I just opened https://github.com/ACWI-SSWD/nldi-crawler/issues/126 to track the issue.

**Comment by dblodgett-usgs** [comment]
FYI -- @cheginit the site that was the original source of this issue has been fixed. https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-04127918?f=json

**Comment by cheginit** [comment]
That's great! Thanks.
