### ISSUE TITLE
Basin area discrepancy between NLDI and NHD

### ISSUE THREAD

**Issue by cheginit** [internetofwater/ref_gages#27]
I found two USGS stations where the area of the NLDI's delineated basin geometry is way off compared to the total drainage area provided by NHD. The IDs are:

- USGS-01446000: NLDI area is 307 sqkm whereas in NHD it's 95 sqkm
- USGS-11295230: NLDI area is 502 sqkm whereas in NHD it's 76 sqkm

**Comment by dblodgett-usgs** [comment]
USGS-01446000 has a stated drainage area of 36.7 sqmi in NWIS which matches NHD.
![image](https://user-images.githubusercontent.com/1492803/221221877-1c887b69-ffc1-476c-a40b-bb5435e5b9ff.png)

This looks like it's got the wrong major river.

USGS-11295230 has a stated drainage area of 29.3 sqmi in NWIS which matches NHD.
![image](https://user-images.githubusercontent.com/1492803/221222872-9f68d0ac-3bce-4df1-a0bf-0a9569ab8743.png)

This looks OK to me... not entirely clear what would be wrong in this case. 

@cheginit -- where are you deriving the NHD identifiers that link gages to the network from?

**Comment by cheginit** [comment]
@dblodgett-usgs I got the associated NHD IDs of the station from the `Gage` layer of the NHDPlus (MR). From this layer, I extracted the NHD areas and IDs of all CONUS stations and put them in a [gist](https://gist.github.com/cheginit/03129c5a0fb57272792aa4165b06fc19).

> When we add up drainage area, we ignore diversions but when we delineate a basin polygon we include all network connections (diversions included).

That's an interesting distinction between the basin polygon and drainage area.

**Comment by dblodgett-usgs** [comment]
Not sure there's really anything to do here. Reopen if you want to follow up.
